sudo: false
language: ruby
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/02e5112c59e387a9d167
      - https://webhooks.gitter.im/e/2cf2b3fce38bfb758c65
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
rvm:
     - 2.1
before_install:
    - gem install travis
#install:
#    - echo "y" | travis login --org --github-token $GH_TOKEN
